#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  sudo install_usb_udev_rules.sh \
    --roboteq /dev/ttyUSB0 \
    --front   /dev/ttyUSB2 \
    --back    /dev/ttyUSB1

The arguments identify the devices only during this one-time installation.
The generated udev rules create these persistent names:
  /dev/roboteq
  /dev/lidar_front
  /dev/lidar_back

The installer prefers a unique USB serial number. If a device has no unique
serial number, it uses the physical USB port path (ID_PATH), so that device
must remain connected to the same physical USB port.
USAGE
}

ROBOTEQ_SOURCE="/dev/ttyUSB0"
FRONT_SOURCE="/dev/ttyUSB2"
BACK_SOURCE="/dev/ttyUSB1"
RULES_FILE="/etc/udev/rules.d/99-pharmarobot-usb.rules"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --roboteq)
      ROBOTEQ_SOURCE="${2:?Missing value for --roboteq}"
      shift 2
      ;;
    --front)
      FRONT_SOURCE="${2:?Missing value for --front}"
      shift 2
      ;;
    --back)
      BACK_SOURCE="${2:?Missing value for --back}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "This installer must run as root. Re-running with sudo..."
  exec sudo -- "$0" \
    --roboteq "$ROBOTEQ_SOURCE" \
    --front "$FRONT_SOURCE" \
    --back "$BACK_SOURCE"
fi

for command in udevadm readlink awk grep install; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "Required command not found: $command" >&2
    exit 1
  }
done

names=(roboteq lidar_front lidar_back)
sources=("$ROBOTEQ_SOURCE" "$FRONT_SOURCE" "$BACK_SOURCE")
resolved=()
serial_short=()
serial_full=()
paths=()

property_value() {
  local properties="$1"
  local key="$2"
  awk -F= -v wanted="$key" '$1 == wanted {sub(/^[^=]*=/, ""); print; exit}' <<<"$properties"
}

for i in "${!sources[@]}"; do
  source_device="${sources[$i]}"

  if [[ ! -e "$source_device" ]]; then
    echo "Device does not exist: $source_device" >&2
    exit 1
  fi

  real_device="$(readlink -f "$source_device")"
  if [[ ! -c "$real_device" ]]; then
    echo "Not a character device: $source_device -> $real_device" >&2
    exit 1
  fi

  properties="$(udevadm info --query=property --name="$real_device")"

  resolved+=("$real_device")
  serial_short+=("$(property_value "$properties" ID_SERIAL_SHORT)")
  serial_full+=("$(property_value "$properties" ID_SERIAL)")
  paths+=("$(property_value "$properties" ID_PATH)")
done

if [[ "${resolved[0]}" == "${resolved[1]}" || \
      "${resolved[0]}" == "${resolved[2]}" || \
      "${resolved[1]}" == "${resolved[2]}" ]]; then
  echo "The Roboteq, front LiDAR and back LiDAR must resolve to three distinct devices." >&2
  printf 'Resolved devices: %s\n' "${resolved[@]}" >&2
  exit 1
fi

count_value() {
  local wanted="$1"
  shift
  local count=0 value
  for value in "$@"; do
    [[ -n "$wanted" && "$value" == "$wanted" ]] && ((count += 1))
  done
  printf '%s' "$count"
}

udev_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

rules=(
  '# PharmaRobot persistent serial-device names.'
  '# Generated by install_usb_udev_rules.sh; do not hand-edit while devices are remapped.'
)

for i in "${!names[@]}"; do
  match_key=""
  match_value=""

  if [[ -n "${serial_short[$i]}" ]] && \
     [[ "$(count_value "${serial_short[$i]}" "${serial_short[@]}")" -eq 1 ]]; then
    match_key="ID_SERIAL_SHORT"
    match_value="${serial_short[$i]}"
  elif [[ -n "${serial_full[$i]}" ]] && \
       [[ "$(count_value "${serial_full[$i]}" "${serial_full[@]}")" -eq 1 ]]; then
    match_key="ID_SERIAL"
    match_value="${serial_full[$i]}"
  elif [[ -n "${paths[$i]}" ]]; then
    match_key="ID_PATH"
    match_value="${paths[$i]}"
  else
    echo "Cannot derive a stable identity for ${sources[$i]}." >&2
    echo "The device has no unique serial number and no ID_PATH." >&2
    exit 1
  fi

  escaped_value="$(udev_escape "$match_value")"
  rules+=(
    "# ${names[$i]}: ${sources[$i]} -> ${resolved[$i]} using ${match_key}=${match_value}"
    "SUBSYSTEM==\"tty\", ENV{${match_key}}==\"${escaped_value}\", SYMLINK+=\"${names[$i]}\", GROUP=\"dialout\", MODE=\"0660\""
  )
done

printf '%s\n' "${rules[@]}" | install -m 0644 /dev/stdin "$RULES_FILE"

udevadm control --reload-rules
udevadm trigger --subsystem-match=tty --action=add
udevadm settle

printf '\nInstalled %s\n\n' "$RULES_FILE"
cat "$RULES_FILE"

printf '\nPersistent-device verification:\n'
failed=0
for i in "${!names[@]}"; do
  link="/dev/${names[$i]}"
  if [[ ! -e "$link" ]]; then
    echo "  MISSING: $link"
    failed=1
    continue
  fi

  actual="$(readlink -f "$link")"
  expected="${resolved[$i]}"
  printf '  %-18s -> %s' "$link" "$actual"
  if [[ "$actual" == "$expected" ]]; then
    echo "  [OK]"
  else
    echo "  [WRONG: expected $expected]"
    failed=1
  fi
done

if [[ $failed -ne 0 ]]; then
  echo >&2
  echo "One or more persistent device names were not created correctly." >&2
  echo "Unplug/replug the affected USB device, then run check_usb_devices.sh." >&2
  exit 1
fi

echo
echo "Stable USB device names installed successfully."
echo "If ID_PATH was used, keep that device connected to the same physical USB port."
